-- Email/password is the only member-login factor. This display-only ID is
-- generated by Owner Studio; existing one-way hashes cannot be recovered.
alter table public.detective_member_applications
  add column if not exists member_id_display text;
